# Generated by Django 2.2.2 on 2019-06-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.TextField(default='325 W Adams Blvd, Los Angeles CA, 90007'),
            preserve_default=False,
        ),
    ]
